# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: ghcr.io
  repository: telest0
  tag: v1.2.1-edd813d
  arch: amd64
  os: linux
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
secret:
  name: kbot
  env: TELE_TOKEN
  key: token